name: Paste Special Plugin Continous Integration
on: [push, pull_request]
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm install
      - run: npm run dist
      - run: npm test